# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'ProjectFrameworkDemo' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for ProjectFrameworkDemo
    pod 'CYLTabBarController', '~> 1.17.4'
    pod 'SDCycleScrollView','~> 1.66'
    pod 'IQKeyboardManager'
    pod 'SVProgressHUD'
    pod 'ReactiveObjC'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'Toast'
    pod 'YYKit'
    pod 'QMUIKit', '~> 2.7.4'

    pod 'MLTransition', '~> 2.1.2'#滑动返回

    pod 'UMCCommon'
    #pod 'UMCSecurityPlugins'
    #     U-Share SDK UI模块（分享面板，建议添加、、、、、、、、、、）
    pod 'UMCShare/UI'
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'
    # 集成新浪微博(精简版1M)
    pod 'UMCShare/Social/ReducedSina'


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            end
        end
    end
end
